var kRecipes = {
  // Breakfast.
  'blueberry_pancakes': 'Blueberry Pancakes',
  'nalesniki': 'Nalesniki',
  'waffles_banana_choco': 'Chocolate Banana Waffles',
  // Breads.
  'brazilian_cheese_bread': 'Brazilian Cheese Bread',
  'bread_beer': 'Beer Bread',
  'bread_potato': 'Potato Bread',
  'corn_bread': 'Corn Bread',
  // Soups.
  'barszcz_z_uszkami': 'Barszcz z Uszkami',
  'soup_butternut_squash': 'Butternut Squash Soup',
  'soup_chicken_noodle': 'Chicken Noodle Soup',
  'soup_coconut': 'Coconut Soup',
  'soup_minestrone': 'Minestrone Soup',
  'soup_onion': 'Onion Soup',
  'soup_red_lentil': 'Red Lentil Soup',
  'soup_udon_noodle': 'Udon Noodle Soup with Bok Choy and Poached Egg',
  // Salads.
  'salad_kale_apple_cheese': 'Kale Apple Cheese Salad',
  // Sides.
  'rice_basmati': 'Basmati Rice',
  'pesto': 'Pesto',
  'potato_salad': 'Potato Salad',
  'potatoes_mashed': 'Mashed Potatoes',
  'roasted_brussel_sprouts_with_garlic': 'Roasted Brussel Sprouts with Garlic',
  'salatka_jarzynowa': 'Salatka Jarzynowa',
  'scallion_pancakes': 'Scallion Pancakes',
  'snow_pea_shoots': 'Snow Pea Shoots',
  'stuffing': 'Stuffing',
  // Mains.
  'chicken_butter': 'Butter Chicken',
  'chicken_marsala': 'Chicken Marsala',
  'chicken_piccata': 'Chicken Piccata',
  'chile_verde': 'Chile Verde',
  'dahl': 'Dahl',
  'hot_sour_chickpeas': 'Hot & Sour Chickpeas',
  'kopytka': 'Kopytka',
  'lasagna_banana': 'Banana Lasagna',
  'lasagna_vegetable': 'Vegetable Lasagna',
  'lentil_bolognese_sauce': 'Lentil Bolognese Sauce',
  'moussaka': 'Moussaka',
  'mujadara': 'Mujadara',
  'muttar_paneer': 'Muttar Paneer',
  'pad_thai': 'Pad Thai',
  'pasta_primavera': 'Pasta Primavera',
  'persian_green_stew': 'Persian Green Stew',
  'pierogi': 'Pierogi',
  'salad_life_alive': 'Life Alive Salad',
  'thai_red_curry': 'Thai Red Curry with Kabocha',
  'three_cheese_pasta_bake': 'Three Cheese Pasta Bake',
  // Desserts.
  'banana_bread': 'Banana Bread',
  'brownie_cheesecake': 'Brownie Cheesecake',
  'cake_carrot': 'Carrot Cake',
  'cake_szarlotka_z_budyniem': 'Szarlotka z Budyniem',
  'cookies_applesauce_oatmeal': 'Applesauce Oatmeal Cookies',
  'cookies_drela': 'Drela Cookies',
  'cookies_matcha': 'Matcha Cookies',
  'cookies_thumbprint': 'Thumbprint Cookies',
  'horchata': 'Horchata',
  'mango_sticky_rice': 'Mango Sticky Rice',
  'pie_apple': 'Apple Pie',
  'rice_pudding': 'Rice Pudding',
  // Other.
  'gravy_pan': 'Pan Gravy',
  'roast_turkey': 'Roast Turkey',
  'sauce_cranberry': 'Cranberry Sauce',
};

// Groupings for index.
var kIndex = {
  'Breakfast': [
    'blueberry_pancakes',
    'nalesniki',
    'waffles_banana_choco',
  ],
  'Bread': [
    'brazilian_cheese_bread',
    'bread_beer',
    'bread_potato',
    'corn_bread',
  ],
  'Salads': [
    'salad_kale_apple_cheese',
  ],
  'Sides': [
    'rice_basmati',
    'pesto',
    'roasted_brussel_sprouts_with_garlic',
    'potato_salad',
    'salatka_jarzynowa',
    'scallion_pancakes',
    'snow_pea_shoots',
    'stuffing',
  ],
  'Soups': [
    'barszcz_z_uszkami',
    'soup_butternut_squash',
    'soup_coconut',
    'soup_chicken_noodle',
    'soup_minestrone',
    'soup_onion',
    'soup_red_lentil',
    'soup_udon_noodle',
  ],
  'Mains': [
    'chicken_butter',
    'chicken_marsala',
    'chicken_piccata',
    'chile_verde',
    'dahl',
    'hot_sour_chickpeas',
    'kopytka',
    'lasagna_banana',
    'lasagna_vegetable',
    'lentil_bolognese_sauce',
    'moussaka',
    'mujadara',
    'muttar_paneer',
    'pad_thai',
    'pasta_primavera',
    'persian_green_stew',
    'pierogi',
    'salad_life_alive',
    'thai_red_curry',
    'three_cheese_pasta_bake',
  ],
  'Desserts': [
    'banana_bread',
    'brownie_cheesecake',
    'cake_carrot',
    'cake_szarlotka_z_budyniem',
    'cookies_applesauce_oatmeal',
    'cookies_drela',
    'cookies_matcha',
    'cookies_thumbprint',
    'horchata',
    'mango_sticky_rice',
    'pie_apple',
    'rice_pudding',
  ],
  'Thanksgiving': [
    'roast_turkey',
    'roasted_brussel_sprouts_with_garlic',
    'gravy_pan',
    'sauce_cranberry',
    'stuffing',
    'potatoes_mashed',
    'pie_apple',
  ],
};
