var kRecipes = {
  // Breakfast.
  'nalesniki': 'Nalesniki',
  'pancakes_blueberry': 'Blueberry Pancakes',
  'pancakes_sourdough': 'Sourdough Pancakes (or Waffles)',
  'waffles_banana_choco': 'Chocolate Banana Waffles',
  // Breads.
  'brazilian_cheese_bread': 'Brazilian Cheese Bread',
  'bread_beer': 'Beer Bread',
  'corn_bread': 'Corn Bread',
  'scones_spanakopita': 'Spanakopita Scones',
  'sandwiches': 'Sandwich Ideas',
  // Soups.
  'barszcz_z_uszkami': 'Barszcz z Uszkami',
  'soup_butternut_squash': 'Butternut Squash Soup',
  'soup_chicken_noodle': 'Chicken Noodle Soup',
  'soup_matzo_ball': 'Matzo Ball Soup',
  'soup_minestrone': 'Minestrone Soup',
  'soup_red_lentil': 'Red Lentil Soup',
  'soup_udon_noodle': 'Udon Noodle Soup with Bok Choy and Poached Egg',
  // Salads.
  'salad_celery_date': 'Celery Salad with Dates, Almonds, and Parmesan',
  'salad_kale_apple_cheese': 'Kale Apple Cheese Salad',
  // Sides.
  'rice_basmati': 'Basmati Rice',
  'rice_mexican': 'Mexican Rice',
  'pilaf_quinoa_lentil': 'Lentil Quinoa Pilaf',
  'mushrooms_stuffed_swiss_chard': 'Stuffed Mushrooms with Swiss Chard',
  'pesto': 'Pesto',
  'potato_salad': 'Potato Salad',
  'potatoes_mashed': 'Mashed Potatoes',
  'roasted_brussel_sprouts_with_garlic': 'Roasted Brussel Sprouts with Garlic',
  'salatka_jarzynowa': 'Salatka Jarzynowa',
  'scallion_pancakes': 'Scallion Pancakes',
  'snow_pea_shoots': 'Snow Pea Shoots',
  'stuffing': 'Stuffing',
  // Mains.
  'chicken_butter': 'Butter Chicken',
  'chicken_marsala': 'Chicken Marsala',
  'chicken_piccata': 'Chicken Piccata',
  'chile_verde': 'Chile Verde',
  'hot_sour_chickpeas': 'Hot & Sour Chickpeas',
  'kopytka': 'Kopytka',
  'lasagna_banana': 'Banana Lasagna',
  'lasagna_vegetable': 'Vegetable Lasagna',
  'moussaka': 'Moussaka',
  'mujadara': 'Mujadara',
  'muttar_paneer': 'Muttar Paneer',
  'pad_thai': 'Pad Thai',
  'panda_express_tofu_squash': 'Panda Express Tofu Squash',
  'pasta_primavera': 'Pasta Primavera',
  'pasta_shells_and_cheese': 'Quick Shells and Cheese',
  'pierogi': 'Pierogi',
  'pizza_cast_iron': 'Cast Iron Pizza',
  'salad_life_alive': 'Life Alive Salad',
  'tacos_fish': 'Fish Tacos',
  'thai_red_curry': 'Thai Red Curry with Kabocha',
  'three_cheese_pasta_bake': 'Three Cheese Pasta Bake',
  // Desserts.
  'banana_bread': 'Banana Bread',
  'bar_strawberry': 'Strawberry Bar',
  'brownie_cheesecake': 'Brownie Cheesecake',
  'cake_carrot': 'Carrot Cake',
  'cake_lava': 'Lava Cake',
  'cake_lemon_poppyseed': 'Lemon Poppyseed Cake',
  'cake_mochi': 'Mochi Cake',
  'cake_murzynek': 'Murzynek',
  'cake_szarlotka_z_budyniem': 'Szarlotka z Budyniem',
  'chalka_z_kruszonka': 'Chalka z Kruszonka',
  'cookies_applesauce_oatmeal': 'Applesauce Oatmeal Cookies',
  'cookies_drela': 'Drela Cookies',
  'cookies_matcha': 'Matcha Cookies',
  'cookies_thumbprint': 'Thumbprint Cookies',
  'mango_sticky_rice': 'Mango Sticky Rice',
  'pie_apple': 'Apple Pie',
  // Other.
  'gravy_pan': 'Pan Gravy',
  'roast_turkey': 'Roast Turkey',
  'sauce_cranberry': 'Cranberry Sauce',
};

// Groupings for index.
var kIndex = {
  'Breakfast': [
    'nalesniki',
    'pancakes_blueberry',
    'pancakes_sourdough',
    'waffles_banana_choco',
  ],
  'Bread': [
    'brazilian_cheese_bread',
    'bread_beer',
    'corn_bread',
    'sandwiches',
    'scones_spanakopita',
  ],
  'Salads': [
    'salad_celery_date',
    'salad_kale_apple_cheese',
  ],
  'Sides': [
    'rice_basmati',
    'rice_mexican',
    'pilaf_quinoa_lentil',
    'mushrooms_stuffed_swiss_chard',
    'pesto',
    'roasted_brussel_sprouts_with_garlic',
    'potato_salad',
    'salatka_jarzynowa',
    'scallion_pancakes',
    'snow_pea_shoots',
    'stuffing',
  ],
  'Soups': [
    'barszcz_z_uszkami',
    'soup_butternut_squash',
    'soup_chicken_noodle',
    'soup_matzo_ball',
    'soup_minestrone',
    'soup_red_lentil',
    'soup_udon_noodle',
  ],
  'Mains': [
    'chicken_butter',
    'chicken_marsala',
    'chicken_piccata',
    'chile_verde',
    'hot_sour_chickpeas',
    'kopytka',
    'lasagna_banana',
    'lasagna_vegetable',
    'moussaka',
    'mujadara',
    'muttar_paneer',
    'pad_thai',
    'panda_express_tofu_squash',
    'pasta_primavera',
    'pasta_shells_and_cheese',
    'pizza_cast_iron',
    'pierogi',
    'salad_life_alive',
    'tacos_fish',
    'thai_red_curry',
    'three_cheese_pasta_bake',
  ],
  'Desserts': [
    'banana_bread',
    'bar_strawberry',    
    'brownie_cheesecake',
    'cake_carrot',
    'cake_mochi',
    'cake_lava',
    'cake_lemon_poppyseed',
    'cake_murzynek',
    'cake_szarlotka_z_budyniem',
    'chalka_z_kruszonka',
    'cookies_applesauce_oatmeal',
    'cookies_drela',
    'cookies_matcha',
    'cookies_thumbprint',
    'mango_sticky_rice',
    'pie_apple',
  ],
  'Thanksgiving': [
    'roast_turkey',
    'roasted_brussel_sprouts_with_garlic',
    'gravy_pan',
    'sauce_cranberry',
    'stuffing',
    'potatoes_mashed',
    'pie_apple',
  ],
};
