var kRecipes = {
  // Breakfast.
  'nalesniki': 'Nalesniki',
  'waffles_banana_choco': 'Chocolate Banana Waffles',
  // Breads.
  'brazilian_cheese_bread': 'Brazilian Cheese Bread',
  'bread_beer': 'Beer Bread',
  'bread_potato': 'Potato Bread',
  'corn_bread': 'Corn Bread',
  // Soups.
  'barszcz_z_uszkami': 'Barszcz z Uszkami',
  'soup_butternut_squash': 'Butternut Squash Soup',
  'soup_coconut': 'Coconut Soup',
  'soup_onion': 'Onion Soup',
  'soup_red_lentil': 'Red Lentil Soup',
  'soup_udon_noodle': 'Udon Noodle Soup with Bok Choy and Poached Egg',
  // Salads.
  'salad_kale_apple_cheese': 'Kale Apple Cheese Salad',
  // Sides.
  'potato_salad': 'Potato Salad',
  'roasted_brussel_sprouts_with_garlic': 'Roasted Brussel Sprouts with Garlic',
  'salatka_jarzynowa': 'Salatka Jarzynowa',
  'stuffing': 'Stuffing',
  // Mains.
  'chicken_marsala': 'Chicken Marsala',
  'chicken_piccata': 'Chicken Piccata',
  'chile_verde': 'Chile Verde',
  'dahl': 'Dahl',
  'hot_sour_chickpeas': 'Hot & Sour Chickpeas',
  'kopytka': 'Kopytka',
  'lasagna_banana': 'Banana Lasagna',
  'lasagna_vegetable': 'Vegetable Lasagna',
  'lentil_bolognese_sauce': 'Lentil Bolognese Sauce',
  'moussaka': 'Moussaka',
  'muttar_paneer': 'Muttar Paneer',
  'pad_thai': 'Pad Thai',
  'pasta_primavera': 'Pasta Primavera',
  'persian_green_stew': 'Persian Green Stew',
  'pierogi': 'Pierogi',
  'salad_life_alive': 'Life Alive Salad',
  'thai_red_curry': 'Thai Red Curry with Kabocha',
  'three_cheese_pasta_bake': 'Three Cheese Pasta Bake',
  // Desserts.
  'banana_bread': 'Banana Bread',
  'brownie_cheesecake': 'Brownie Cheesecake',
  'cake_carrot': 'Carrot Cake',
  'cake_szarlotka_z_budyniem': 'Szarlotka z Budyniem',
  'cookies_applesauce_oatmeal': 'Applesauce Oatmeal Cookies',
  'cookies_drela': 'Drela Cookies',
  'horchata': 'Horchata',
  'mango_sticky_rice': 'Mango Sticky Rice',
  'rice_pudding': 'Rice Pudding',
};

// Groupings for index.
var kIndex = {
  'Breakfast': [
    'nalesniki',
    'waffles_banana_choco',
  ],
  'Bread': [
    'brazilian_cheese_bread',
    'bread_beer',
    'bread_potato',
    'corn_bread',
  ],
  'Salads': [
    'salad_kale_apple_cheese',
  ],
  'Sides': [
    'roasted_brussel_sprouts_with_garlic',
    'potato_salad',
    'salatka_jarzynowa',
    'stuffing',
  ],
  'Soups': [
    'barszcz_z_uszkami',
    'soup_butternut_squash',
    'soup_coconut',
    'soup_onion',
    'soup_red_lentil',
    'soup_udon_noodle',
  ],
  'Mains': [
    'chicken_marsala',
    'chicken_piccata',
    'chile_verde',
    'dahl',
    'hot_sour_chickpeas',
    'kopytka',
    'lasagna_banana',
    'lasagna_vegetable',
    'lentil_bolognese_sauce',
    'moussaka',
    'muttar_paneer',
    'pad_thai',
    'pasta_primavera',
    'persian_green_stew',
    'pierogi',
    'salad_life_alive',
    'thai_red_curry',
    'three_cheese_pasta_bake',
  ],
  'Desserts': [
    'banana_bread',
    'brownie_cheesecake',
    'cake_carrot',
    'cake_szarlotka_z_budyniem',
    'cookies_applesauce_oatmeal',
    'cookies_drela',
    'horchata',
    'mango_sticky_rice',
    'rice_pudding',
  ],
};
